### ISSUE TITLE
FR :  Facebook checkins.

### ISSUE THREAD

**Issue by danito** [diplix/OwnYourCheckin#3]
FB checkins : https://github.com/snarfed/ownyourcheckin
When I add a location to an instagram, isn't this a checkin rather than a simple photo...?

**Comment by diplix** [comment]
sure, any post or note with a location could be considered a checkin.
but why is this an issue? is there anything i can do to resolve this?

**Comment by danito** [comment]
not an issue, just a FR : feature request.
Thinking about it : the remark about IG should be handled at the endpoint for ownyourgram, discard this.

**Comment by diplix** [comment]
sorry, still not sure what feture you requested :) 
until i do, i close the issue.

**Comment by danito** [comment]
duplicate of #4 ;-)
